#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
if npx lint-staged; then
  echo "Linting passed."
else
  echo "Linting failed. Please fix the errors and try again."
  exit 1
fi
